#!/bin/bash
if [ "$1" == "dockerinfo" ]; then
version=$(docker info | grep ' Server Version: ' | sed -r 's/ Server Version: //g')
containers=$(docker info | grep ' Containers: ' | sed -r 's/ Containers: //g')
running=$(docker info | grep '  Running: ' | sed -r 's/  Running: //g')
ddriver=$(docker info | grep ' Storage Driver: ' | sed -r 's/ Storage Driver: //g')
os=$(docker info | grep ' Operating System: ' | sed -r 's/ Operating System: //g')
ram=$(docker info | grep ' Total Memory: ' | sed -r 's/ Total Memory: //g' | cut -f1 -d ".")
hostname=$(docker info | grep ' Name: ' | sed -r 's/ Name: //g')
virtd=$(hostnamectl | grep Virtualization | sed -r 's/Virtualization://g' | sed -r 's/ //g')
cpumodel=$(lscpu | grep 'Model name:' | sed -r 's/Model name:            //g')
cpus=$(docker info | grep ' CPUs: ' | sed -r 's/ CPUs: //g')

echo '[{"version":'$version',"running":"'$running'","ddriver":"'$ddriver'","os":'$os',"ram":'$ram',"virtd":'$virtd',"cpumodel":'$cpumodel',"cpus":'$cpus'}]';
fi
